site_name: Fire★ Documentation
theme: readthedocs
nav:
  - Home: 'index.md'
  - 'Quickstart Guid': quickstart.md
  - Connecting: connecting.md
  - 'Installing Apps': 'installing_apps.md'
  - 'Creating Apps':
    - 'Creating Apps': 'api/index.md'
    - 'Hello World Tutorial': 'api/hello_world.md'
    - 'Simple Chat Tutorial': 'api/chat.md'
    - 'API Reference': 'api/reference.md'
