name: firestr
version: '0.11.1'
summary: The Grass Computing Platform
description: |
    Communicate with your friends and family over a secure P2P connection.
    Create and share P2P applications easily using the Lua programming language.

grade: stable
confinement: strict
base: core20
icon: src/gui/resources/firestr.svg

environment:
    PULSE_RUNTIME_PATH: /var/run/pulse
    PULSE_SYSTEM: 1

parts:
  firestr:
    source: .
    plugin: cmake
    build-packages:
        - qtbase5-dev  
        - qtmultimedia5-dev
        - libqt5svg5-dev
        - libboost-system-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-regex-dev
        - libboost-thread-dev
        - uuid-dev
        - libgmp-dev
        - libssl-dev
        - libxss-dev
        - libbotan-2-dev
        - libopus-dev
        - libsnappy-dev
    stage-packages:
        - libpulse0
        - libasound2
        - locales-all
        - libqt5gui5
        - libqt5core5a
        - libqt5svg5
        - libqt5widgets5
        - libqt5network5
        - libqt5multimedia5
        - libqt5multimedia5-plugins
        - libqt5multimediawidgets5
        - libxss1
        - libopus0
        - libsnappy1v5
        - libtspi1
        - libbotan-2-12
    after: [desktop/qt5]

  desktop/qt5:
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - appmenu-qt5

apps:
    firestr:
        command: desktop-launch firestr
        desktop: share/applications/firestr.desktop
        plugs:
            - x11
            - unity7
            - home
            - opengl
            - pulseaudio
            - network
            - network-bind
            - gsettings
