name: firestr
version: '0.11.2'
summary: The Grass Computing Platform
description: |
    Communicate with your friends and family over a secure P2P connection.
    Create and share P2P applications easily using the Lua programming language.

grade: stable
confinement: strict
base: core22
icon: src/gui/resources/firestr.svg

environment:
    PULSE_RUNTIME_PATH: /var/run/pulse
    PULSE_SYSTEM: 1

parts:
  firestr:
    source: https://github.com/mempko/firestr.git
    plugin: cmake
    build-packages:
        - qt6-base-dev  
        - qt6-multimedia-dev
        - libqt6svg6-dev
        - libboost-system-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-regex-dev
        - libboost-thread-dev
        - uuid-dev
        - libgmp-dev
        - libssl-dev
        - libxss-dev
        - libbotan-2-dev
        - libopus-dev
        - libsnappy-dev
    stage-packages:
        - libpulse0
        - libasound2
        - locales-all
        - libqt6gui6
        - libqt6core6
        - libqt6svg6
        - libqt6widgets6
        - libqt6network6
        - libqt6multimedia6
        - libqt6multimediawidgets6
        - libxss1
        - libopus0
        - libsnappy1v5
        - libtspi1
        - libbotan-2-12
apps:
    firestr:
        command: usr/local/bin/firestr
        desktop: usr/local/share/applications/firestr.desktop
        extensions: [kde]
        plugs:
            - x11
            - unity7
            - home
            - opengl
            - pulseaudio
            - network
            - network-bind
            - gsettings
